### ISSUE TITLE
想请教一下：能否在群发之后，能够自动进行再回复？

### ISSUE THREAD

**Issue by winglight** [yizhiren/wechat-qunfa#1]
比如：我群发给A：亲爱的A，中秋快乐！对方回复：也祝你节日快乐！然后，可以继续自动回复：[表情-微笑]或者其他内容，甚至自动接入一个机器人~~~

**Comment by DevinXian** [comment]
这个自己研究吧，另外呢楼主把async不当做npm包来使用...略奇葩

**Comment by yizhiren** [comment]
@winglight 参考这段：

wechat.on('text-message', function(msg) {
	var fromUser = msg.FromUserName;
	var msgContent = msg.Content;
	if(fromUser.substr(0,2) == '@@'){
		console.log('text-message', 'from group', msgContent);
	}else{
		var replyMsg = '[auto reply]\n' + ' I can repeat your voice!\n' + msgContent;
		console.log('text-message', 'from friend', msgContent);
		wechat.sendMsg(replyMsg,fromUser);
	}
	

})

**Comment by yizhiren** [comment]
@DevinXian 当时npm install 失败，一气之下

**Comment by winglight** [comment]
@yizhiren 看代码大概明白意思了，不过这些微信事件及数据格式有没有文档可以参考一下的？

**Comment by yizhiren** [comment]
@winglight 看这个 https://github.com/Urinx/WeixinBot/blob/master/README.md

**Comment by winglight** [comment]
@yizhiren Thx a lot！我还以为会是微信官方文档，结果居然是个程序员妹子整理的，非常详细，我不熟悉Python，还是用你的版本比较方便，反正接口是一样的

**Comment by yizhiren** [comment]
@winglight 我看了她的实现，准备移植下他的机器人部分的逻辑

**Comment by winglight** [comment]
@yizhiren 顶一个！
