### ISSUE TITLE
不支持多用户啊，而且不能扫描之后没有跳转

### ISSUE THREAD

**Issue by moxiaobei2** [yizhiren/wechat-qunfa#2]
启动方式初始化，每次刷新之后又不可以重新取数据，无法用户使用。

**Comment by yizhiren** [comment]
１．　
我理解的你的意思是：如果登陆两个用户，第一个用户的联系人信息会被第二个用户的联系人覆盖？
如果是这样，是可以处理的，调用接口wechat.getFriendList()就可以获取联系人信息(请首先npm update更新)．

else if('friend'===msg.Content){
 +    console.log('command friend recognize');
 +    var myfriends = wechat.getFriendList();
 +    console.log('myfriend',myfriends);
 +    console.log('friend number:',myfriends.length);
    }

２．扫描之后跳转问题，我的建议是登陆第一个之后，在login事件或者init-message事件中调用wechat2.start()登陆第二个用户．
